In [2]:
import numpy as np

In [18]:
x = np.array([[1,9,4],[2,3,4]])
for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'9'
b'4'
b'2'
b'3'
b'4'


In [26]:
x = np.array([[1,9,4],[2,3,4]])
for i in np.ndenumerate(x):
    print(i)

((0, 0), 1)
((0, 1), 9)
((0, 2), 4)
((1, 0), 2)
((1, 1), 3)
((1, 2), 4)


In [30]:
# copy  view concatinate stack vstack dstack hstack array_split
# search
#where ,searchsorted,sort
print(np.where(x == 10))
print(np.sort(x))

(array([], dtype=int64), array([], dtype=int64))
[[1 4 9]
 [2 3 4]]


In [41]:
# shuffle unique resize. flatten revel
var = np.array([1,2,3,4,4,4])
np.random.shuffle(var)
u = np.unique(var,return_index=True,return_counts=True,return_inverse=True)
print(u)
print(var)
print(np.resize(var,(2,3)))

(array([1, 2, 3, 4]), array([0, 4, 2, 1]), array([0, 3, 2, 3, 1, 3]), array([1, 1, 1, 3]))
[1 4 3 4 2 4]
[[1 4 3]
 [4 2 4]]


In [43]:
# insert delete
var1 = np.array([1,2,3,4,5])
i = np.insert(var1,(2,3),[4,20])# same as 2d with axis
print(i)

[ 1  2  4  3 20  4  5]


In [60]:
# matrix 
varm = np.matrix([[1,2],[4,5]])
print(varm.T)
print(var1.swapaxes(0,0))
print(np.linalg.inv(varm))
print(np.linalg.matrix_power(varm,-1))
print(np.linalg.det(varm))


[[1 4]
 [2 5]]
[1 2 3 4 5]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
-2.9999999999999996


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3128c5e9-85ba-4136-aeb8-73f1853178e0' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>